"""TaskStore protocol definition."""
from __future__ import annotations

from typing import Protocol, List, Optional

from soul_speak.sto.models import Task, TaskLog


class TaskStoreProtocol(Protocol):
    def create_task(self, task: Task) -> None: ...
    def get_task(self, task_id: str) -> Optional[Task]: ...
    def list_tasks(self) -> List[Task]: ...
    def update_task(self, task: Task) -> None: ...
    def append_log(self, log: TaskLog) -> None: ...
    def list_logs(self, task_id: str) -> List[TaskLog]: ...


__all__ = ["TaskStoreProtocol"]
